image: ubuntu:xenial

before_script:


stages:
  - prepare_docker
  - test
  - test-package

prepare_docker:
  stage: prepare_docker
  image: docker:latest
  script: 
    - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN $CI_REGISTRY
    - docker build --pull -t $CI_REGISTRY_IMAGE:ci -f $CI_PROJECT_DIR/ci/Dockerfile .
    - docker push $CI_REGISTRY_IMAGE:ci

test:
  stage: test
  image: $CI_REGISTRY_IMAGE:ci
  script:
    - echo SHMDATA BUILD
    - git clone https://github.com/sat-metalab/shmdata.git libshmdata
    - cd libshmdata
    - mkdir build
    - cd build
    - cmake ..
    - make -j"$(nproc)"
    - make install
    - ldconfig
    - cd ../..
    - mkdir build
    - cd build
    - cmake ..
    - make -j"$(nproc)"
    - make test

test-package:
  stage: test-package
  image: $CI_REGISTRY_IMAGE:ci
  script:
    - echo SHMDATA BUILD
    - git clone https://github.com/sat-metalab/shmdata.git libshmdata
    - cd libshmdata
    - mkdir build
    - cd build
    - cmake ..
    - make -j"$(nproc)"
    - make install
    - ldconfig
    - cd ../..
    - mkdir build
    - cd build
    - cmake ..
    - make package_source_test
  only:
    - develop
    - master
